spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/JavaEELabs?serverTimezone=GMT%2B8
    username: root
    password: 123456
    type: com.mysql.cj.jdbc.MysqlConnectionPoolDataSource
    hikari:
      max-lifetime: 600000
      minimum-idle: 3
      maximum-pool-size: 400
      connection-timeout: 30000
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 1000

    lettuce:
      pool:
        max-active: 200
        min-idle: 0
        max-idle: 200
        max-wait: -1

server:
  tomcat:
    threads:
      max: 500
  port: 8080


mybatis:
  type-aliases-package: com.haruki.lab3.model
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
